# .github/workflows/firebase-cron.yml
name: Codzienne wywołanie Firebase Function

on:
  schedule:
    - cron: '0 5 * * *'  # codziennie o 5:00 UTC

jobs:
  run-daily-function:
    runs-on: ubuntu-latest
    steps:
      - name: Wywołaj funkcję Firebase
        run: curl -X GET https://us-central1-TWOJ_PROJEKT.cloudfunctions.net/doSomething
